name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-lab-app ./app

      - name: Test Docker image
        run: docker run -d -p 8080:80 --name devops-test devops-lab-app

      - name: Test application
        run: curl http://localhost:8080

      - name: Stop container
        run: docker stop devops-test